name: deep-raman
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.15.0
  - astor=0.8.1
  - blas=1.0
  - blosc=1.21.0
  - brotli=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.26
  - cached-property=1.5.2
  - certifi=2021.10.8
  - cfitsio=3.470
  - charls=2.2.0
  - cloudpickle=2.0.0
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2021.10.0
  - dataclasses=0.8
  - fonttools=4.25.0
  - freetype=2.11.0
  - fsspec=2022.1.0
  - gast=0.2.2
  - giflib=5.2.1
  - google-pasta=0.2.0
  - grpcio=1.42.0
  - h5py=3.6.0
  - hdf5=1.10.6
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - importlib-metadata=4.8.2
  - intel-openmp=2021.4.0
  - joblib=1.1.0
  - jpeg=9d
  - jxrlib=1.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libcurl=7.80.0
  - libcxx=12.0.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgfortran=3.0.1
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libprotobuf=3.19.1
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libzopfli=1.0.3
  - llvm-openmp=12.0.0
  - locket=0.2.1
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib-base=3.5.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - networkx=2.6.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1m
  - opt_einsum=3.3.0
  - packaging=21.3
  - partd=1.2.0
  - pillow=8.4.0
  - pip=21.2.2
  - plotly=5.1.0
  - protobuf=3.19.1
  - pyparsing=3.0.4
  - python=3.7.11
  - python-dateutil=2.8.2
  - pywavelets=1.1.1
  - pyyaml=6.0
  - readline=8.1.2
  - scikit-image=0.18.3
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=58.0.4
  - six=1.15.0
  - snappy=1.1.8
  - sqlite=3.37.2
  - tenacity=8.0.1
  - tensorboard=2.0.0
  - tensorflow=2.0.0
  - tensorflow-base=2.0.0
  - tensorflow-estimator=2.0.0
  - termcolor=1.1.0
  - threadpoolctl=2.2.0
  - tifffile=2021.7.2
  - tk=8.6.11
  - toolz=0.11.2
  - typing_extensions=3.10.0.2
  - werkzeug=2.0.2
  - wheel=0.37.1
  - wrapt=1.13.3
  - xz=5.2.5
  - yaml=0.2.5
  - zfp=0.5.5
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9
